version: '3.8'

services:
  web:
    build: . # Build from the Dockerfile in the current directory
    container_name: telegram-pastebin-web
    command: python app.py # Command to run the Flask web server
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    volumes:
      - ./messages.json:/app/messages.json # Persist message history
    env_file:
      - ./.env # Load environment variables from the .env file
    depends_on:
      - bot # Ensure the bot starts before the web server (optional, but good practice)
    restart: unless-stopped # Always restart unless explicitly stopped

  bot:
    build: . # Build from the Dockerfile in the current directory
    container_name: telegram-pastebin-bot
    command: python bot.py # Command to run the Telegram bot
    volumes:
      - ./messages.json:/app/messages.json # Access the same message history
    env_file:
      - ./.env # Load environment variables from the .env file
    restart: unless-stopped # Always restart unless explicitly stopped

networks:
  default:
    driver: bridge # Use a default bridge network for container communication