version: '3.8'

services:
  web:
    build: .
    container_name: telegram-pastebin-web
    command: python app.py
    ports:
      - "80:5000"
    volumes:
      - ./messages.db:/app/messages.db # <--- CHANGE THIS LINE
    env_file:
      - ./.env
    depends_on:
      - bot
    restart: unless-stopped

  bot:
    build: .
    container_name: telegram-pastebin-bot
    command: python bot.py
    volumes:
      - ./messages.db:/app/messages.db # <--- CHANGE THIS LINE
    env_file:
      - ./.env
    restart: unless-stopped

networks:
  default:
    driver: bridge